name: Build and Export MCP Image

# 一樣設定為手動觸發
on:
  workflow_dispatch: 

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Inject CA
        run: echo "${{ secrets.FET_CA_CERT }}" > company-ca.crt

      - name: Build Docker image
        run: docker build -t tableau-mcp:latest .

      - name: Save Docker image to a tar archive
        run: docker save -o tableau-mcp.tar tableau-mcp:latest

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tableau-mcp-image
          path: tableau-mcp.tar
          retention-days: 1 # 檔案保留 1 天供下載
